services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-network

  app:
    image: payment-service
    build: .
    ports:
      - "7001:7001"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - db
    networks:
      - payment-network

volumes:
  postgres_data:

networks:
  payment-network:

